REJECT THIS COMMIT
ClipboardHealth/actions pull request #9
Opened 2022-08-16 16:44 UTC by pgbezerra

2022-08-22 03:46 UTC, nimboya approved these changes

2022-08-23 14:40 UTC, blankmanch requested changes

2022-08-23 17:07 UTC, pgbezerra commented on .github/actions/sync-branches/src/branch.ts
> +    const result = /^(?<branch_name>.*)?(?<action>__\w+?__)$/.exec(item);
What do you mean?
We need to get `__ASC__` or `__DESC__` and the branch name.

2022-08-23 17:07 UTC, pgbezerra commented on .github/actions/sync-branches/dist/index.js
> +import './sourcemap-register.cjs';import { createRequire as __WEBPACK_EXTERNAL_createRequire } from "module";
Unfortunately, there is no way to tell Github Actions to download the js code somewhere else, so we have to commit the dist on the repo itself.

2022-08-23 20:20 UTC, pgbezerra commented
I have to merge this now.
So I'll skip the other reviewer.

2022-08-23 20:21 UTC, merged